This notebook was used to develop the `saveMeasurement()` method as a general tool for saving calibration and test measurements in an organized fashion

The module is duplicated in saveCalData.py to be importable as a Python module into other code

In [59]:
import datetime
import numpy as np
import os
import pandas as pd
from glob import glob

In [39]:
def createHeader(sn, measurementName, trial, columns, sep='\t'):    
    headerStr = f'sn: {sn}\nmeasurement: {measurementName}\ntrial: {trial}\n{sep.join(columns)}'
    return headerStr

In [69]:
print(createHeader(20480001, 'dacCal', 1, ['current', 'dacCode'], sep='\t'))

sn: 20480001
measurement: dacCal
trial: 1
current	dacCode


In [65]:
def saveMeasurement(dest, sn, measurementName, data, columns, header=None, fmt='%.6e'):
    folder = os.path.join(dest, measurementName)
    if not os.path.exists(folder):
        os.makedirs(folder)
    # search for existing measurements of this type and increment the measurement counter
    filesForThisSn = glob(os.path.join(folder, f'{sn}_{measurementName}*.csv'))
    trial = 1 + len(filesForThisSn)
    fname = f'{sn}_{measurementName}_{trial}.csv'
    if header==None:
        hdr = createHeader(sn, measurementName, trial, columns)
    np.savetxt(os.path.join(dest, measurementName, fname), np.transpose(data), delimiter='\t', header=hdr, fmt=fmt)

In [42]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [43]:
y = np.random.randn(10)
y

array([ 0.05100533,  0.45048817, -1.11488017, -1.32694716, -2.3091467 ,
        1.2315014 , -0.55202076, -2.41561286, -2.15572617,  0.73752181])

In [70]:
z = np.random.randn(10)*1.7
z

array([ 1.21106303, -2.73116381, -1.44270169, -0.07927471, -0.55836756,
       -2.96023793,  2.40556992, -0.78699427,  0.23745825,  0.43834971])

In [44]:
sn = 20480001
mment = 'test'
trial = 1

In [71]:
saveMeasurement('.\CalData', sn, mment, [x, y, z], ['x', 'y', 'z'])